"""Added user table

Revision ID: 67f8cfccb111
Revises: 188cb8e2a3a6
Create Date: 2022-01-13 15:13:14.565492

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67f8cfccb111'
down_revision = 'a8b49c00de03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
        sa.Column('output_filename', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('source', sa.String(), nullable=False),
        sa.Column('status', sa.Integer(), nullable=False),
        sa.Column('task_begin', sa.DateTime(), nullable=True),
        sa.Column('task_end', sa.DateTime(), nullable=True),
        sa.Column('progress', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('output_filename')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    # ### end Alembic commands ###
