"""Add column video_id and rename column output_filename,source

Revision ID: 6c9104e46c04
Revises: 67f8cfccb111
Create Date: 2022-01-14 14:29:12.031906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c9104e46c04'
down_revision = '67f8cfccb111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('video_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.add_column('records', sa.Column('output_name', sa.String(), nullable=False))
    op.add_column('records', sa.Column('source_name', sa.String(), nullable=False))
    op.drop_column('records', 'output_filename')
    op.drop_column('records', 'source')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('records', sa.Column('output_filename', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('records', 'source_name')
    op.drop_column('records', 'output_name')
    op.drop_column('records', 'video_id')
    # ### end Alembic commands ###
