"""Added description

Revision ID: a8b49c00de03
Revises: 4e7a7bb8bfd7
Create Date: 2021-11-25 15:51:10.914748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8b49c00de03'
down_revision = '4e7a7bb8bfd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('description', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'description')
    # ### end Alembic commands ###
