"""empty message

Revision ID: c90cf7ea489d
Revises: 3ecd6464df41
Create Date: 2021-10-07 15:32:35.991198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c90cf7ea489d'
down_revision = '3ecd6464df41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_videos',
    sa.Column('video_id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('quality', sa.String(), nullable=True),
    sa.Column('task_begin', sa.DateTime(), nullable=True),
    sa.Column('task_end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.add_column('videos', sa.Column('task_begin', sa.DateTime(), nullable=True))
    op.add_column('videos', sa.Column('task_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'task_end')
    op.drop_column('videos', 'task_begin')
    op.drop_table('download_videos')
    # ### end Alembic commands ###
