"""empty message

Revision ID: ef7804b7aad7
Revises: c90cf7ea489d
Create Date: 2021-10-14 17:18:59.925971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef7804b7aad7'
down_revision = 'c90cf7ea489d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('download_videos', sa.Column('filename', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('download_videos', 'filename')
    # ### end Alembic commands ###
